export type GuestItem = {
  id: number;
  name: string;
  category: string;
  price: number;
  emoji: string;
  veg: boolean;
  bestseller?: boolean;
  desc?: string;
  prepMin?: number;
  spice?: 1 | 2 | 3;
  allergens?: string[];
  variants?: { id: string; label: string; delta: number }[];
  addons?: { id: string; label: string; price: number }[];
};

export const guestCategories = [
  { key: 'all', label: 'All', emoji: '✨' },
  { key: 'Bestsellers', label: 'Bestsellers', emoji: '⭐' },
  { key: 'Appetizers', label: 'Starters', emoji: '🥟' },
  { key: 'Pizza', label: 'Pizza', emoji: '🍕' },
  { key: 'Burgers', label: 'Burgers', emoji: '🍔' },
  { key: 'Pasta', label: 'Pasta', emoji: '🍝' },
  { key: 'Mains', label: 'Mains', emoji: '🍽️' },
  { key: 'Salads', label: 'Salads', emoji: '🥗' },
  { key: 'Sushi', label: 'Sushi', emoji: '🍣' },
  { key: 'Indian', label: 'Indian', emoji: '🍛' },
  { key: 'Asian', label: 'Asian', emoji: '🍜' },
  { key: 'Desserts', label: 'Desserts', emoji: '🍰' },
  { key: 'Beverages', label: 'Drinks', emoji: '🥤' },
  { key: 'Wines', label: 'Wines', emoji: '🍷' },
  { key: 'Cocktails', label: 'Cocktails', emoji: '🍸' },
];

export const guestItems: GuestItem[] = [
  {
    id: 1,
    name: 'Margherita',
    category: 'Pizza',
    price: 4.5,
    emoji: '🍕',
    veg: true,
    bestseller: true,
    desc: 'San Marzano tomato · fior di latte · basil',
    prepMin: 14,
    allergens: ['Gluten', 'Dairy'],
    variants: [
      { id: 'small', label: '7"', delta: -1.5 },
      { id: 'medium', label: '11"', delta: 0 },
      { id: 'large', label: '14"', delta: 2.5 },
    ],
    addons: [
      { id: 'cheese', label: 'Extra cheese', price: 0.8 },
      { id: 'olives', label: 'Black olives', price: 0.5 },
      { id: 'mushrooms', label: 'Mushrooms', price: 0.7 },
    ],
  },
  {
    id: 2,
    name: 'Pepperoni',
    category: 'Pizza',
    price: 5.0,
    emoji: '🍕',
    veg: false,
    desc: 'Spicy pepperoni · mozzarella',
    prepMin: 14,
    spice: 2,
    allergens: ['Gluten', 'Dairy'],
  },
  {
    id: 3,
    name: 'Truffle Burger',
    category: 'Burgers',
    price: 5.9,
    emoji: '🍔',
    veg: false,
    bestseller: true,
    desc: 'Beef · truffle aioli · brioche bun',
    prepMin: 12,
    allergens: ['Gluten', 'Egg'],
    variants: [
      { id: 'single', label: 'Single patty', delta: 0 },
      { id: 'double', label: 'Double patty', delta: 1.5 },
    ],
  },
  {
    id: 4,
    name: 'Classic Cheeseburger',
    category: 'Burgers',
    price: 4.0,
    emoji: '🍔',
    veg: false,
    prepMin: 10,
    allergens: ['Gluten', 'Dairy'],
  },
  {
    id: 5,
    name: 'Veggie Burger',
    category: 'Burgers',
    price: 3.8,
    emoji: '🍔',
    veg: true,
    desc: 'House patty · avocado · slaw',
    prepMin: 10,
    allergens: ['Gluten'],
  },
  {
    id: 6,
    name: 'Caesar Salad',
    category: 'Salads',
    price: 3.3,
    emoji: '🥗',
    veg: true,
    desc: 'Romaine · parmesan · croutons',
    prepMin: 6,
    allergens: ['Gluten', 'Dairy'],
  },
  {
    id: 7,
    name: 'Greek Salad',
    category: 'Salads',
    price: 3.0,
    emoji: '🥗',
    veg: true,
    prepMin: 6,
    allergens: ['Dairy'],
  },
  {
    id: 8,
    name: 'Burrata',
    category: 'Salads',
    price: 4.5,
    emoji: '🧀',
    veg: true,
    desc: 'Tomato · basil · olive oil',
    prepMin: 4,
    allergens: ['Dairy'],
  },
  {
    id: 9,
    name: 'Carbonara',
    category: 'Pasta',
    price: 4.2,
    emoji: '🍝',
    veg: false,
    prepMin: 11,
    allergens: ['Gluten', 'Dairy', 'Egg'],
  },
  {
    id: 10,
    name: 'Penne Arrabbiata',
    category: 'Pasta',
    price: 3.8,
    emoji: '🍝',
    veg: true,
    spice: 2,
    prepMin: 10,
    allergens: ['Gluten'],
  },
  {
    id: 11,
    name: 'Lasagna',
    category: 'Pasta',
    price: 4.6,
    emoji: '🍝',
    veg: false,
    desc: 'Slow-cooked beef ragù',
    prepMin: 15,
    allergens: ['Gluten', 'Dairy'],
  },
  {
    id: 12,
    name: 'Sushi Set',
    category: 'Sushi',
    price: 7.5,
    emoji: '🍣',
    veg: false,
    bestseller: true,
    desc: '12-piece chef selection',
    prepMin: 14,
    allergens: ['Fish', 'Soy'],
  },
  {
    id: 13,
    name: 'Spicy Tuna Roll',
    category: 'Sushi',
    price: 5.5,
    emoji: '🍣',
    veg: false,
    spice: 2,
    prepMin: 9,
    allergens: ['Fish', 'Soy'],
  },
  {
    id: 14,
    name: 'Salmon Nigiri',
    category: 'Sushi',
    price: 6.0,
    emoji: '🍣',
    veg: false,
    prepMin: 8,
    allergens: ['Fish'],
  },
  {
    id: 15,
    name: 'Tiramisu',
    category: 'Desserts',
    price: 2.5,
    emoji: '🍰',
    veg: true,
    prepMin: 3,
    allergens: ['Dairy', 'Egg'],
  },
  {
    id: 16,
    name: 'Cheesecake',
    category: 'Desserts',
    price: 2.8,
    emoji: '🍰',
    veg: true,
    prepMin: 3,
    allergens: ['Dairy'],
  },
  {
    id: 17,
    name: 'Brownie',
    category: 'Desserts',
    price: 1.8,
    emoji: '🍫',
    veg: true,
    prepMin: 3,
    allergens: ['Gluten', 'Dairy', 'Egg'],
  },
  {
    id: 18,
    name: 'Ice Cream Sundae',
    category: 'Desserts',
    price: 2.2,
    emoji: '🍨',
    veg: true,
    prepMin: 4,
    allergens: ['Dairy'],
  },
  {
    id: 19,
    name: 'Pinot Noir',
    category: 'Wines',
    price: 6.0,
    emoji: '🍷',
    veg: true,
    desc: 'Glass · 175ml',
    prepMin: 1,
  },
  {
    id: 20,
    name: 'Chardonnay',
    category: 'Wines',
    price: 5.5,
    emoji: '🥂',
    veg: true,
    prepMin: 1,
  },
  {
    id: 21,
    name: 'Prosecco',
    category: 'Wines',
    price: 6.5,
    emoji: '🍾',
    veg: true,
    prepMin: 1,
  },
  {
    id: 22,
    name: 'Old Fashioned',
    category: 'Cocktails',
    price: 5.0,
    emoji: '🥃',
    veg: true,
    prepMin: 4,
  },
  {
    id: 23,
    name: 'Negroni',
    category: 'Cocktails',
    price: 5.0,
    emoji: '🍸',
    veg: true,
    prepMin: 4,
  },
  {
    id: 24,
    name: 'Mojito',
    category: 'Cocktails',
    price: 4.0,
    emoji: '🍹',
    veg: true,
    bestseller: true,
    prepMin: 5,
  },
  {
    id: 25,
    name: 'Mango Lassi',
    category: 'Beverages',
    price: 1.5,
    emoji: '🥭',
    veg: true,
    prepMin: 2,
    allergens: ['Dairy'],
  },
  {
    id: 26,
    name: 'Masala Chai',
    category: 'Beverages',
    price: 0.8,
    emoji: '🍵',
    veg: true,
    prepMin: 4,
    allergens: ['Dairy'],
  },
  {
    id: 27,
    name: 'Iced Coffee',
    category: 'Beverages',
    price: 1.5,
    emoji: '🧊',
    veg: true,
    prepMin: 3,
  },
  {
    id: 28,
    name: 'Espresso',
    category: 'Beverages',
    price: 1.0,
    emoji: '☕',
    veg: true,
    prepMin: 2,
  },
  {
    id: 29,
    name: 'Cappuccino',
    category: 'Beverages',
    price: 1.5,
    emoji: '☕',
    veg: true,
    bestseller: true,
    prepMin: 3,
    allergens: ['Dairy'],
  },
  {
    id: 30,
    name: 'Sparkling Water',
    category: 'Beverages',
    price: 1.5,
    emoji: '💧',
    veg: true,
    prepMin: 1,
  },
  {
    id: 31,
    name: 'Lemonade',
    category: 'Beverages',
    price: 1.5,
    emoji: '🍋',
    veg: true,
    prepMin: 2,
  },
  {
    id: 32,
    name: 'Chicken Tikka',
    category: 'Indian',
    price: 4.5,
    emoji: '🍗',
    veg: false,
    spice: 2,
    prepMin: 14,
    allergens: ['Dairy'],
  },
  {
    id: 33,
    name: 'Butter Chicken',
    category: 'Indian',
    price: 5.0,
    emoji: '🍛',
    veg: false,
    bestseller: true,
    desc: 'House-special · creamy',
    prepMin: 15,
    spice: 1,
    allergens: ['Dairy', 'Nuts'],
  },
  {
    id: 34,
    name: 'Paneer Tikka',
    category: 'Indian',
    price: 4.0,
    emoji: '🧀',
    veg: true,
    spice: 2,
    prepMin: 12,
    allergens: ['Dairy'],
  },
  {
    id: 35,
    name: 'Garlic Naan',
    category: 'Indian',
    price: 1.2,
    emoji: '🫓',
    veg: true,
    prepMin: 4,
    allergens: ['Gluten', 'Dairy'],
  },
  {
    id: 36,
    name: 'Pad Thai',
    category: 'Asian',
    price: 4.0,
    emoji: '🍜',
    veg: false,
    spice: 1,
    prepMin: 10,
    allergens: ['Soy', 'Nuts', 'Egg'],
  },
  {
    id: 37,
    name: 'Ramen',
    category: 'Asian',
    price: 4.5,
    emoji: '🍜',
    veg: false,
    prepMin: 12,
    allergens: ['Gluten', 'Soy'],
  },
  {
    id: 38,
    name: 'Dim Sum Platter',
    category: 'Asian',
    price: 5.0,
    emoji: '🥟',
    veg: false,
    prepMin: 12,
    allergens: ['Gluten', 'Soy'],
  },
  {
    id: 39,
    name: 'Spring Rolls',
    category: 'Appetizers',
    price: 2.0,
    emoji: '🥟',
    veg: true,
    prepMin: 7,
    allergens: ['Gluten'],
  },
  {
    id: 40,
    name: 'Buffalo Wings',
    category: 'Appetizers',
    price: 3.5,
    emoji: '🍗',
    veg: false,
    spice: 2,
    prepMin: 11,
    allergens: ['Dairy'],
  },
  {
    id: 41,
    name: 'Bruschetta',
    category: 'Appetizers',
    price: 2.5,
    emoji: '🍞',
    veg: true,
    prepMin: 5,
    allergens: ['Gluten'],
  },
  {
    id: 42,
    name: 'Calamari Fritti',
    category: 'Appetizers',
    price: 3.8,
    emoji: '🦑',
    veg: false,
    prepMin: 9,
    allergens: ['Gluten'],
  },
  {
    id: 43,
    name: 'Grilled Salmon',
    category: 'Mains',
    price: 7.0,
    emoji: '🐟',
    veg: false,
    prepMin: 16,
    allergens: ['Fish'],
  },
  {
    id: 44,
    name: 'Steak Frites',
    category: 'Mains',
    price: 8.5,
    emoji: '🥩',
    veg: false,
    bestseller: true,
    prepMin: 18,
    variants: [
      { id: 'mr', label: 'Medium-rare', delta: 0 },
      { id: 'mw', label: 'Medium-well', delta: 0 },
      { id: 'wd', label: 'Well done', delta: 0 },
    ],
  },
  {
    id: 45,
    name: 'Roast Chicken',
    category: 'Mains',
    price: 5.5,
    emoji: '🍗',
    veg: false,
    prepMin: 16,
  },
  {
    id: 46,
    name: 'Mushroom Risotto',
    category: 'Mains',
    price: 4.8,
    emoji: '🍚',
    veg: true,
    prepMin: 14,
    allergens: ['Dairy'],
  },
];
